# Generated by Django 4.2.5 on 2023-10-02 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('send_at', models.DateTimeField()),
                ('text_message', models.TextField(blank=True, max_length=1000, null=True)),
                ('mobile_code', models.CharField(max_length=3)),
                ('send_before', models.DateTimeField()),
            ],
        ),
    ]
