# Generated by Django 4.2.5 on 2023-10-03 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_client_id_alter_message_id_alter_newsletter_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsletter',
            old_name='send_at',
            new_name='send_end',
        ),
        migrations.RenameField(
            model_name='newsletter',
            old_name='send_before',
            new_name='send_start',
        ),
    ]
